In [1]:
RAW_PATH = r"C:\Users\Tarun\OneDrive\Desktop\College_PowerBi\Week_2_CyberAttack\Data"

In [20]:
EXPORT_FOLDER = r"C:\Users\Tarun\OneDrive\Desktop\College_PowerBi\Week_2_CyberAttack\Outputs"

In [3]:
import pandas as pd
import numpy as np
import os

In [4]:
df = pd.read_csv("C:/Users/Tarun/OneDrive/Desktop/College_PowerBi/Week_2_CyberAttack/Data/Cyberattacks_Detection.csv")

C:\Users\Tarun\AppData\Local\Temp\ipykernel_11460\362617007.py:1: DtypeWarning: Columns (15) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("C:/Users/Tarun/OneDrive/Desktop/College_PowerBi/Week_2_CyberAttack/Data/Cyberattacks_Detection.csv")

In [5]:
df = pd.read_csv("C:/Users/Tarun/OneDrive/Desktop/College_PowerBi/Week_2_CyberAttack/Data/Cyberattacks_Detection.csv", low_memory=False)
print(f"✅ Loaded: {df.shape[0]:,} rows × {df.shape[1]} cols")

✅ Loaded: 100,000 rows × 16 cols

In [6]:
df.head()

,Attack ID,Source IP,Destination IP,Source Country,Destination Country,Protocol,Source Port,Destination Port,Attack Type,Payload Size (bytes),Detection Label,Confidence Score,ML Model,Affected System,Port Type,Timestamp
0,1.0,68.156.227.194,194.91.121.112,India,USA,ICMP,16824.0,53410.0,Brute Force,3936.0,Detected,0.600507,K-Nearest Neighbors,Cloud Storage,Other,NaN
1,2.0,249.221.229.41,3.207.120.235,Germany,USA,TCP,23977.0,31745.0,Advanced Persistent Threat (APT),2870.0,Detected,0.524150,K-Nearest Neighbors,Network Router,Other,NaN
2,4.0,154.55.209.171,132.115.33.82,USA,China,UDP,36556.0,38880.0,Cross-Site Scripting (XSS) Attack,3833.0,Not Detected,0.238944,Neural Network,Workstation,Other,NaN
3,5.0,106.61.204.27,40.61.49.130,France,France,UDP,14724.0,21669.0,Insider Threat,4301.0,Not Detected,0.122334,Neural Network,Workstation,Other,NaN
4,6.0,144.190.250.125,34.68.66.192,South Korea,Germany,TCP,44693.0,6474.0,Watering Hole Attack,4569.0,Detected,0.970895,Neural Network,Application Server,Other,NaN

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Attack ID             99940 non-null  float64
 1   Source IP             99950 non-null  object
 2   Destination IP        99945 non-null  object
 3   Source Country        99950 non-null  object
 4   Destination Country   99947 non-null  object
 5   Protocol              99941 non-null  object
 6   Source Port           99949 non-null  float64
 7   Destination Port      99946 non-null  float64
 8   Attack Type           99941 non-null  object
 9   Payload Size (bytes)  99947 non-null  float64
 10  Detection Label       99933 non-null  object
 11  Confidence Score      99946 non-null  float64
 12  ML Model              99939 non-null  object
 13  Affected System       99954 non-null  object
 14  Port Type             99939 non-null  object
 15  Timestamp             9826 non-null   object
dtypes: float64(5), object(11)
memory usage: 12.2+ MB

In [8]:
# This shows the column names and their positions
for i, col in enumerate(df.columns):
    print(f"Index {i}: {col}")

Index 0: Attack ID
Index 1: Source IP
Index 2: Destination IP
Index 3: Source Country
Index 4: Destination Country
Index 5: Protocol
Index 6: Source Port
Index 7: Destination Port
Index 8: Attack Type
Index 9: Payload Size (bytes)
Index 10: Detection Label
Index 11: Confidence Score
Index 12: ML Model
Index 13: Affected System
Index 14: Port Type
Index 15: Timestamp

In [9]:
df.isnull().sum()

Attack ID                  60
Source IP                  50
Destination IP             55
Source Country             50
Destination Country        53
Protocol                   59
Source Port                51
Destination Port           54
Attack Type                59
Payload Size (bytes)       53
Detection Label            67
Confidence Score           54
ML Model                   61
Affected System            46
Port Type                  61
Timestamp               90174
dtype: int64

In [10]:
df['Attack Type'].value_counts()

Attack Type
DNS Tunneling                                       5121
Cross-Site Scripting (XSS) Attack                   5094
Malware                                             5071
Ping of Death                                       5039
Email Spam                                          5029
Insider Threat                                      5028
Advanced Persistent Threat (APT)                    5023
Drive-by Download                                   5019
Cryptojacking                                       5016
Man-in-the-Middle (MITM)                            5004
Distributed Denial of Service (DDoS)                5002
Credential Stuffing                                 4985
Simple Network Management Protocol (SNMP) Attack    4981
Zero-Day Exploit                                    4976
Phishing                                            4975
Brute Force                                         4960
Watering Hole Attack                                4922
File Transfer Protocol (FTP) Attack                 4918
Remote Desktop Protocol (RDP) Attack                4900
SQL Injection                                       4878
Name: count, dtype: int64

In [11]:
before = len(df)
df.dropna(how='all', inplace=True)
print(f"Dropped {before - len(df)} fully-empty rows. Remaining: {len(df):,}")

Dropped 0 fully-empty rows. Remaining: 100,000

In [12]:
df.columns = (
    df.columns
    .str.strip()
    .str.title()                          # keeps Power BI column names readable
    .str.replace(r'\s+', ' ', regex=True) # collapse double spaces
)
print("Columns:", list(df.columns))

Columns: ['Attack Id', 'Source Ip', 'Destination Ip', 'Source Country', 'Destination Country', 'Protocol', 'Source Port', 'Destination Port', 'Attack Type', 'Payload Size (Bytes)', 'Detection Label', 'Confidence Score', 'Ml Model', 'Affected System', 'Port Type', 'Timestamp']

In [13]:
# Ports and Attack ID were loaded as float64 because of nulls — convert to Int64 (nullable int)
for col in ['Attack Id', 'Source Port', 'Destination Port']:
    df[col] = pd.to_numeric(df[col], errors='coerce').astype('Int64')

# Payload Size and Confidence Score stay as float
for col in ['Payload Size (Bytes)', 'Confidence Score']:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df.dtypes

Attack Id                 Int64
Source Ip                object
Destination Ip           object
Source Country           object
Destination Country      object
Protocol                 object
Source Port               Int64
Destination Port          Int64
Attack Type              object
Payload Size (Bytes)    float64
Detection Label          object
Confidence Score        float64
Ml Model                 object
Affected System          object
Port Type                object
Timestamp                object
dtype: object

In [14]:
# ── Categorical columns → fill with 'Unknown'
cat_cols = [
    'Source Ip', 'Destination Ip',
    'Source Country', 'Destination Country',
    'Protocol', 'Attack Type', 'Detection Label',
    'Ml Model', 'Affected System', 'Port Type'
]
for col in cat_cols:
    if col in df.columns:
        df[col] = df[col].fillna('Unknown').str.strip()

# ── Numeric columns → fill with median
num_cols = ['Source Port', 'Destination Port', 'Payload Size (Bytes)', 'Confidence Score']
for col in num_cols:
    if col in df.columns:
        df[col] = df[col].fillna(df[col].median())

print("Nulls remaining:")
df.isnull().sum()

Nulls remaining:

Attack Id                  60
Source Ip                   0
Destination Ip              0
Source Country              0
Destination Country         0
Protocol                    0
Source Port                 0
Destination Port            0
Attack Type                 0
Payload Size (Bytes)        0
Detection Label             0
Confidence Score            0
Ml Model                    0
Affected System             0
Port Type                   0
Timestamp               90174
dtype: int64

In [15]:
# Timestamp has ~90k nulls — parse what we can, leave the rest as NaT
df['Timestamp'] = pd.to_datetime(df['Timestamp'], errors='coerce')

# Extract useful parts for analysis
df['Attack Date']  = df['Timestamp'].dt.date
df['Attack Year']  = df['Timestamp'].dt.year
df['Attack Month'] = df['Timestamp'].dt.month_name()
df['Attack Hour']  = df['Timestamp'].dt.hour
df['Day Of Week']  = df['Timestamp'].dt.day_name()

print(f"Valid timestamps: {df['Timestamp'].notna().sum():,}")
print(f"Missing timestamps (NaT): {df['Timestamp'].isna().sum():,}")

Valid timestamps: 9,826
Missing timestamps (NaT): 90,174

In [16]:
# Binary detection flag (easier for charts)
df['Is Detected'] = df['Detection Label'].str.strip().str.lower().map(
    {'detected': 1, 'not detected': 0}
).fillna(-1).astype(int)

# Payload size bucket
df['Payload Bucket'] = pd.cut(
    df['Payload Size (Bytes)'],
    bins=[0, 1_000, 10_000, 50_000, 100_000, float('inf')],
    labels=['< 1 KB', '1–10 KB', '10–50 KB', '50–100 KB', '> 100 KB']
)

# Confidence tier
df['Confidence Tier'] = pd.cut(
    df['Confidence Score'],
    bins=[0, 0.4, 0.7, 1.01],
    labels=['Low', 'Medium', 'High']
)

df[['Detection Label', 'Is Detected', 'Payload Bucket', 'Confidence Tier']].head(10)

  Detection Label  Is Detected Payload Bucket Confidence Tier
0        Detected            1        1–10 KB          Medium
1        Detected            1        1–10 KB          Medium
2    Not Detected            0        1–10 KB             Low
3    Not Detected            0        1–10 KB             Low
4        Detected            1        1–10 KB            High
5        Detected            1        1–10 KB            High
6        Detected            1        1–10 KB            High
7    Not Detected            0        1–10 KB          Medium
8    Not Detected            0        1–10 KB             Low
9        Detected            1         < 1 KB            High

In [17]:
before = len(df)
df.drop_duplicates(inplace=True)
df.reset_index(drop=True, inplace=True)
print(f"Duplicates removed: {before - len(df)}")
print(f"Final shape: {df.shape[0]:,} rows × {df.shape[1]} cols")

Duplicates removed: 0
Final shape: 100,000 rows × 24 cols

In [18]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 24 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Attack Id             99940 non-null   Int64
 1   Source Ip             100000 non-null  object
 2   Destination Ip        100000 non-null  object
 3   Source Country        100000 non-null  object
 4   Destination Country   100000 non-null  object
 5   Protocol              100000 non-null  object
 6   Source Port           100000 non-null  Int64
 7   Destination Port      100000 non-null  Int64
 8   Attack Type           100000 non-null  object
 9   Payload Size (Bytes)  100000 non-null  float64
 10  Detection Label       100000 non-null  object
 11  Confidence Score      100000 non-null  float64
 12  Ml Model              100000 non-null  object
 13  Affected System       100000 non-null  object
 14  Port Type             100000 non-null  object
 15  Timestamp             9826 non-null    datetime64[ns]
 16  Attack Date           9826 non-null    object
 17  Attack Year           9826 non-null    float64
 18  Attack Month          9826 non-null    object
 19  Attack Hour           9826 non-null    float64
 20  Day Of Week           9826 non-null    object
 21  Is Detected           100000 non-null  int32
 22  Payload Bucket        100000 non-null  category
 23  Confidence Tier       100000 non-null  category
dtypes: Int64(3), category(2), datetime64[ns](1), float64(4), int32(1), object(13)
memory usage: 16.9+ MB

,Attack Id,Source Ip,Destination Ip,Source Country,Destination Country,Protocol,Source Port,Destination Port,Attack Type,Payload Size (Bytes),...,Port Type,Timestamp,Attack Date,Attack Year,Attack Month,Attack Hour,Day Of Week,Is Detected,Payload Bucket,Confidence Tier
0,1,68.156.227.194,194.91.121.112,India,USA,ICMP,16824,53410,Brute Force,3936.0,...,Other,NaT,NaT,NaN,NaN,NaN,NaN,1,1–10 KB,Medium
1,2,249.221.229.41,3.207.120.235,Germany,USA,TCP,23977,31745,Advanced Persistent Threat (APT),2870.0,...,Other,NaT,NaT,NaN,NaN,NaN,NaN,1,1–10 KB,Medium
2,4,154.55.209.171,132.115.33.82,USA,China,UDP,36556,38880,Cross-Site Scripting (XSS) Attack,3833.0,...,Other,NaT,NaT,NaN,NaN,NaN,NaN,0,1–10 KB,Low
3,5,106.61.204.27,40.61.49.130,France,France,UDP,14724,21669,Insider Threat,4301.0,...,Other,NaT,NaT,NaN,NaN,NaN,NaN,0,1–10 KB,Low
4,6,144.190.250.125,34.68.66.192,South Korea,Germany,TCP,44693,6474,Watering Hole Attack,4569.0,...,Other,NaT,NaT,NaN,NaN,NaN,NaN,1,1–10 KB,High

In [21]:
# Create the folder if it doesn't exist yet
os.makedirs(EXPORT_FOLDER, exist_ok=True)

out_path = os.path.join(EXPORT_FOLDER, 'Cyberattacks_Cleaned.csv')
df.to_csv(out_path, index=False)

print(f"✅ Cleaned dataset saved to:\n   {out_path}")
print(f"   Size: {os.path.getsize(out_path) / 1_000_000:.1f} MB")

✅ Cleaned dataset saved to:
   C:\Users\Tarun\OneDrive\Desktop\College_PowerBi\Week_2_CyberAttack\Outputs\Cyberattacks_Cleaned.csv
   Size: 18.2 MB